---

- debug:
    msg: "SAP note 2002167 Step 4: Linux Kernel Parameters"

# Note: The value for vm.max_map_count of 2147483647 (previously 2000000)
#   is set according to SAP note 900929.
- name: Set kernel parameters kernel.sem and vm.max_map_count
  sysctl:
    sysctl_file: /etc/sysctl.d/sap.conf
    name: "{{ line_item.name }}"
    value: "{{ line_item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: kernel.sem, value: '1250 256000 100 1024' }
    - { name: vm.max_map_count, value: '2147483647' }
  loop_control:
    loop_var: line_item
