---

- debug:
    msg: "imported RedHat/generic/assert-etc-hosts.yml"

# Note: There is no check related to hostname aliases.

#- name: Get all hostname aliases of {{ sap_ip }}
#  shell: |
#    awk '( $1 == "{{ sap_ip }}" ) {
#      for (i=2; i<=NF; ++i) { 
#        if (( $i != "{{ sap_hostname }}" ) && ( $i != "{{ sap_hostname }}.{{ sap_domain }}" )) { printf $i" " } 
#      } 
#    }' /etc/hosts
#  register: sap_base_settings_register_hostname_aliases
#  changed_when: false
#  check_mode: false

#- name: Print hostname aliases
#  debug:
#    var=sap_hostname_aliases

- name: Check if ipv4 address, FQDN, and hostname are once in /etc/hosts
  command: awk 'BEGIN{a=0}/{{ sap_ip }}/&&/{{ sap_hostname }}.{{ sap_domain }}/&&/{{ sap_hostname }}/{a++}END{print a}' /etc/hosts
  register: __shell_01_result
  ignore_errors: yes
  changed_when: no

- name: Assert that ipv4 address, FQDN, and hostname are once in /etc/hosts
  assert:
    that: "__shell_01_result.stdout == '1'"
    fail_msg: "FAIL: The line '{{ sap_ip }} {{ sap_hostname }}.{{ sap_domain }} {{ sap_hostname }}' needs to be once in /etc/hosts!"
    success_msg: "PASS: The line '{{ sap_ip }} {{ sap_hostname }}.{{ sap_domain }} {{ sap_hostname }}' is once in /etc/hosts."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

#- name: Ensure that the entry in /etc/hosts is correct
#  lineinfile:
#    path: /etc/hosts
#    regexp: '^{{ sap_ip }}\s'
#    line: "{{ sap_ip }} {{ sap_hostname }}.{{ sap_domain }} {{ sap_hostname }} {{ sap_base_settings_register_hostname_aliases.stdout }}"
#  when:
#    - sap_preconfigure_assert_modify_etc_hosts | bool

- name: Check for duplicate entries of {{ sap_ip }} in /etc/hosts
  command: awk 'BEGIN{a=0}/{{ sap_ip }}/{a++}END{print a}' /etc/hosts
  register: __shell_02_result
  ignore_errors: yes
  changed_when: no

- name: Assert that there is just one line containing {{ sap_ip }} in /etc/hosts
  assert:
    that: "__shell_02_result.stdout == '1'"
    fail_msg: "FAIL: There is more than one line containing '{{ sap_ip }}' in /etc/hosts!"
    success_msg: "PASS: There is only one line containing '{{ sap_ip }}' in /etc/hosts."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Check for duplicate or missing entries of {{ sap_hostname }}.{{ sap_domain }} in /etc/hosts
  command: awk '/^{{ sap_hostname }}.{{ sap_domain }} /||
                / {{ sap_hostname }}.{{ sap_domain }} /||
                / {{ sap_hostname }}.{{ sap_domain }}$/{a++}END{print a}' /etc/hosts
  register: __shell_03_result
  ignore_errors: yes
  changed_when: no

- name: Assert that there is just one line containing {{ sap_hostname }}.{{ sap_domain }} in /etc/hosts
  assert:
    that: "__shell_03_result.stdout == '1'"
    fail_msg: "FAIL: There is more than one line containing '{{ sap_hostname }}.{{ sap_domain }}' in /etc/hosts!"
    success_msg: "PASS: There is only one line containing '{{ sap_hostname }}.{{ sap_domain }}' in /etc/hosts."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Check for duplicate or missing entries of {{ sap_hostname }} in /etc/hosts
  command: awk '/^{{ sap_hostname }} /||
                / {{ sap_hostname }} /||
                / {{ sap_hostname }}$/{a++}END{print a}' /etc/hosts
  register: __shell_04_result
  ignore_errors: yes
  changed_when: no

- name: Assert that there is just one line containing {{ sap_hostname }} in /etc/hosts
  assert:
    that: "__shell_04_result.stdout == '1'"
    fail_msg: "FAIL: There is more than one line containing '{{ sap_hostname }}' in /etc/hosts!"
    success_msg: "PASS: There is only one line containing '{{ sap_hostname }}' in /etc/hosts."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Check hostname -s
  shell: test "$(hostname -s)" = "$(hostname)"
  register: __hostname_s_result
  ignore_errors: yes
  changed_when: no

- name: Assert that hostname -s matches the output of hostname
  assert:
    that: __hostname_s_result.rc == 0
    fail_msg: "FAIL: The output of 'hostname -s' does not match the output of 'hostname'!"
    success_msg: "PASS: The output of 'hostname -s' matches the output of 'hostname'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Check hostname -f
  shell: test "$(hostname -f)" = "$(hostname).$(hostname -d)"
  register: __hostname_f_result
  ignore_errors: yes
  changed_when: no

- name: Assert that hostname -f matches the output of hostname.hostname -d
  assert:
    that: __hostname_f_result.rc == 0
    fail_msg: "FAIL: The output of 'hostname -f' does not match the output of 'hostname'.'hostname -d'!"
    success_msg: "PASS: The output of 'hostname -f' matches the output of 'hostname'.'hostname -d'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

...
